---
- name: Converge
  hosts: all
  vars:
    prometheus_exporter_list:
      - name: elasticsearch
        download_url: https://github.com/prometheus-community/elasticsearch_exporter/releases/download/v1.3.0/elasticsearch_exporter-1.3.0.linux-amd64.tar.gz
        exec_params: |
          --es.uri=http://elastic:password@elasticsearch:9200 \
          --web.listen-address=0.0.0.0:8080
      - name: logstash
        download_url: https://github.com/sequra/logstash_exporter/releases/download/v7.3.0.0/logstash_exporter-7.3.0.0.linux-amd64.tar.gz
        exec_params: |
          --logstash.endpoint=http://logstash:9600 \
          --web.listen-address=0.0.0.0:8080
  tasks:
    - name: "Include ansible-role-prometheus-exporter"
      include_role:
        name: "ansible-role-prometheus-exporter"
